STABILITY_THRESHOLDS = {
    "structure": 70,
    "power": 70,
    "atmosphere": 70,
    "contamination": 10,
    "communications": 80,
    "health": 70,
}

INITIAL_ENERGY = 100
ENERGY_DRAIN_RATE = 0.3
BASE_DETERIORATION_RATE = 0.3
BASE_FIX_RATE = 1.5
DEFAULT_COMMUNICATION_RANGE = 30

FIRE_INTENSITY_INCREASE_RATE = 1

INITIAL_HEALTH = 50
CRITICAL_HEALTH_THRESHOLD = 30
BASE_INJURE_RATE = 1
BASE_HEALING_RATE = 1
